site_name: ganslate
  

nav:
  
    - Home: index.md
    - Installation: installation.md

    - Package Overview:
        - Commandline Interface: package_overview/1_cli.md
        - ganslate Projects: package_overview/2_projects.md
        - Datasets: package_overview/3_datasets.md
        - Model Architectures and Loss Functions: package_overview/4_architectures.md
        - Engines: package_overview/5_engines.md
        - Logging and Visualization: package_overview/6_trackers.md
        - Configuration: package_overview/7_configuration.md

    - Basic Tutorials:
        - First Run: tutorials_basic/1_first_run_with_aerial2maps.md
        - Your New Project: tutorials_basic/2_new_project.md

    - Advanced Tutorials:
        - Custom GAN Architectures: tutorials_advanced/1_custom_gan_architecture.md
        - Custom Generator and Discriminator Architectures: tutorials_advanced/2_custom_G_and_D_architectures.md

    - API: api/*
        
    - Community:
        - Contributing:  community/contributing.md


theme: readthedocs


markdown_extensions:
    - admonition